### ISSUE TITLE
vendored linters crash with Go 1.9

### ISSUE THREAD

**Issue by pierrre** [alecthomas/gometalinter#300]
I'm currently installing vendors with `gometalinter --install`.
Since Go 1.9 beta1 some linters are failing (silently see #299).

If I use non vendored linters, it works `gometalinter --install --update --no-vendored-linters`

Crash messages:

```
unused .
panic: Package("runtime/cgo").Build(): unsatisfied import: Program.CreatePackage("unsafe") was not called

goroutine 902 [running]:
honnef.co/go/tools/ssa.(*Package).build(0xc42de7a060)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/ssa/builder.go:2304 +0x15bb
honnef.co/go/tools/ssa.(*Package).(honnef.co/go/tools/ssa.build)-fm()
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/ssa/builder.go:2264 +0x2a
sync.(*Once).Do(0xc42de7a08c, 0xc431098798)
	/home/pierre/.gimme/versions/go1.9beta1.src/src/sync/once.go:44 +0xbe
honnef.co/go/tools/ssa.(*Package).Build(0xc42de7a060)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/ssa/builder.go:2264 +0x4c
honnef.co/go/tools/ssa.(*Program).Build.func1(0xc42caed070, 0xc42de7a060)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/ssa/builder.go:2248 +0x2b
created by honnef.co/go/tools/ssa.(*Program).Build
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/ssa/builder.go:2247 +0x11a
```

```
gosimple .
panic: Package("runtime/cgo").Build(): unsatisfied import: Program.CreatePackage("unsafe") was not called

goroutine 897 [running]:
honnef.co/go/tools/ssa.(*Package).build(0xc42c224d80)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/ssa/builder.go:2304 +0x15bb
honnef.co/go/tools/ssa.(*Package).(honnef.co/go/tools/ssa.build)-fm()
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/ssa/builder.go:2264 +0x2a
sync.(*Once).Do(0xc42c224dac, 0xc420029798)
	/home/pierre/.gimme/versions/go1.9beta1.src/src/sync/once.go:44 +0xbe
honnef.co/go/tools/ssa.(*Package).Build(0xc42c224d80)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/ssa/builder.go:2264 +0x4c
honnef.co/go/tools/ssa.(*Program).Build.func1(0xc42a8c7a60, 0xc42c224d80)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/ssa/builder.go:2248 +0x2b
created by honnef.co/go/tools/ssa.(*Program).Build
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/ssa/builder.go:2247 +0x11a
```

```
staticcheck .
panic: Package("runtime/cgo").Build(): unsatisfied import: Program.CreatePackage("unsafe") was not called

goroutine 928 [running]:
honnef.co/go/tools/ssa.(*Package).build(0xc427f8cf00)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/ssa/builder.go:2304 +0x15bb
honnef.co/go/tools/ssa.(*Package).(honnef.co/go/tools/ssa.build)-fm()
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/ssa/builder.go:2264 +0x2a
sync.(*Once).Do(0xc427f8cf2c, 0xc42e7a3798)
	/home/pierre/.gimme/versions/go1.9beta1.src/src/sync/once.go:44 +0xbe
honnef.co/go/tools/ssa.(*Package).Build(0xc427f8cf00)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/ssa/builder.go:2264 +0x4c
honnef.co/go/tools/ssa.(*Program).Build.func1(0xc428a3eb90, 0xc427f8cf00)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/ssa/builder.go:2248 +0x2b
created by honnef.co/go/tools/ssa.(*Program).Build
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/ssa/builder.go:2247 +0x11a
```

```
unparam .
panic: Package("runtime/cgo").Build(): unsatisfied import: Program.CreatePackage("unsafe") was not called

goroutine 995 [running]:
golang.org/x/tools/go/ssa.(*Package).build(0xc42e39cea0)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/golang.org/x/tools/go/ssa/builder.go:2300 +0x15bb
golang.org/x/tools/go/ssa.(*Package).(golang.org/x/tools/go/ssa.build)-fm()
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/golang.org/x/tools/go/ssa/builder.go:2260 +0x2a
sync.(*Once).Do(0xc42e39cecc, 0xc42e884798)
	/home/pierre/.gimme/versions/go1.9beta1.src/src/sync/once.go:44 +0xbe
golang.org/x/tools/go/ssa.(*Package).Build(0xc42e39cea0)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/golang.org/x/tools/go/ssa/builder.go:2260 +0x4c
golang.org/x/tools/go/ssa.(*Program).Build.func1(0xc4254f3f90, 0xc42e39cea0)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/golang.org/x/tools/go/ssa/builder.go:2244 +0x2b
created by golang.org/x/tools/go/ssa.(*Program).Build
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/golang.org/x/tools/go/ssa/builder.go:2243 +0x11a
```

**Comment by alecthomas** [comment]
Have you tried updating the vendored packages with gvt to see if that fixes the issue?

**Comment by pierrre** [comment]
No, can you give me the exact command ?

Le mar. 20 juin 2017 à 21:05, Alec Thomas <notifications@github.com> a
écrit :

**Comment by alecthomas** [comment]
`cd _linters && gvt update -all` (you will need to install gvt first of course)

**Comment by pierrre** [comment]
When I try to install vendored linters:
```
gometalinter --install
Installing:
  misspell
  unconvert
  unparam
  gas
  goconst
  gotype
  lll
  aligncheck
  errcheck
  gosimple
  ineffassign
  dupl
  gocyclo
  goimports
  staticcheck
  structcheck
  unused
  varcheck
  deadcode
  golint
  interfacer
  safesql
../../alecthomas/gometalinter/_linters/src/github.com/mvdan/unparam/check/check.go:28:2: cannot find package "github.com/mvdan/lint" in any of:
	/home/pierre/.gimme/versions/go1.9beta1.src/src/github.com/mvdan/lint (from $GOROOT)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/github.com/mvdan/lint (from $GOPATH)
../../alecthomas/gometalinter/_linters/src/honnef.co/go/tools/simple/lint.go:14:2: cannot find package "honnef.co/go/tools/internal/sharedcheck" in any of:
	/home/pierre/.gimme/versions/go1.9beta1.src/src/honnef.co/go/tools/internal/sharedcheck (from $GOROOT)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/internal/sharedcheck (from $GOPATH)
WARNING: failed to install one or more linters: exit status 1 (installing individually)
../../alecthomas/gometalinter/_linters/src/github.com/mvdan/unparam/check/check.go:28:2: cannot find package "github.com/mvdan/lint" in any of:
	/home/pierre/.gimme/versions/go1.9beta1.src/src/github.com/mvdan/lint (from $GOROOT)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/github.com/mvdan/lint (from $GOPATH)
WARNING: failed to install github.com/mvdan/unparam: exit status 1
../../alecthomas/gometalinter/_linters/src/honnef.co/go/tools/simple/lint.go:14:2: cannot find package "honnef.co/go/tools/internal/sharedcheck" in any of:
	/home/pierre/.gimme/versions/go1.9beta1.src/src/honnef.co/go/tools/internal/sharedcheck (from $GOROOT)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/internal/sharedcheck (from $GOPATH)
WARNING: failed to install honnef.co/go/tools/cmd/gosimple: exit status 1
../../alecthomas/gometalinter/_linters/src/honnef.co/go/tools/staticcheck/lint.go:20:2: cannot find package "honnef.co/go/tools/internal/sharedcheck" in any of:
	/home/pierre/.gimme/versions/go1.9beta1.src/src/honnef.co/go/tools/internal/sharedcheck (from $GOROOT)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/honnef.co/go/tools/internal/sharedcheck (from $GOPATH)
WARNING: failed to install honnef.co/go/tools/cmd/staticcheck: exit status 1
../../alecthomas/gometalinter/_linters/src/github.com/mvdan/interfacer/check.go:19:2: cannot find package "github.com/mvdan/lint" in any of:
	/home/pierre/.gimme/versions/go1.9beta1.src/src/github.com/mvdan/lint (from $GOROOT)
	/home/pierre/go/src/github.com/alecthomas/gometalinter/_linters/src/github.com/mvdan/lint (from $GOPATH)
WARNING: failed to install github.com/mvdan/interfacer/cmd/interfacer: exit status 1
gometalinter: error: failed to install the following linters: github.com/mvdan/unparam, honnef.co/go/tools/cmd/gosimple, honnef.co/go/tools/cmd/staticcheck, github.com/mvdan/interfacer/cmd/interfacer
```

**Comment by pierrre** [comment]
Do you have any news about this ?
For now I'm using non vendored linters, but it's not very "safe".

**Comment by alecthomas** [comment]
Those last errors are because gvt does not automatically vendor new dependencies when updating. You will need to find those dependencies and vendor them.

**Comment by bradleyfalzon** [comment]
Note the honnef repos should be fixed in #285 as it adds `honnef.co/go/tools/internal/sharedcheck` https://github.com/alecthomas/gometalinter/pull/285/commits/83c2703a836e50ebd6f0aa2cd52bb9fddbf92d89#diff-da7a0fb847747be92a0ef3339bb91fa6

**Comment by pierrre** [comment]
After the recent updates, I've tried again to update dependencies.
Only 1 was missing, so I've added it manually with `gvt fetch github.com/mvdan/lint`.
`gometalinter --install` now runs without error.
No issue with Go 1.8.3 or 1.9beta2.

Could you update vendored linters ?
I'm not very familiar with the vendoring process in this project, so I'm not confident enough to submit a PR.

Could you also update all linters to their **latest version** ?
I've noticed some interesting changes.

**Comment by alecthomas** [comment]
This should already be the case if you pull latest master.

**Comment by pierrre** [comment]
I'm sorry, but this issue is not fixed.
My issue is:
- I use Go 1.9beta2
- I use gometalinter with vendored linters (default)
- some linters panic
- they don't panic if I use non vendored linters, or if I update vendored linters manually

**Comment by pierrre** [comment]
This still crashes on master.
What should we do ?
Go 1.9 will be released in 1 month (and beta versions are already available).

As I said
> I'm not very familiar with the vendoring process in this project, so I'm not confident enough to submit a PR.

I could submit a PR, but I'm afraid to break something else.

**Comment by alecthomas** [comment]
I've updated all of the vendored linters and their dependencies. Can you give it another try?

**Comment by pierrre** [comment]
ok, thank you, I will try.

**Comment by pierrre** [comment]
The issue is fixed.
I don't see linters failing anymore with Go 1.9 beta2.
Thank you ! 👍
