### ISSUE TITLE
Updating from v1 to v2 fails

### ISSUE THREAD

**Issue by stevenh** [alecthomas/gometalinter#406]
We're trying to update to version 2 from version 1 but it fails when trying to run --install
```shell
go get -u gopkg.in/alecthomas/gometalinter.v2
gometalinter.v2 --install
Installing:
  deadcode
  dupl
  errcheck
  gas
  goconst
  gocyclo
  goimports
  golint
  gosimple
  gotype
  gotypex
  ineffassign
  interfacer
  lll
  maligned
  megacheck
  misspell
  nakedret
  safesql
  staticcheck
  structcheck
  unconvert
  unparam
  unused
  varcheck
  vet
can't load package: package honnef.co/go/tools/cmd/megacheck: cannot find package "honnef.co/go/tools/cmd/megacheck" in any of:
        /usr/local/go/src/honnef.co/go/tools/cmd/megacheck (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/honnef.co/go/tools/cmd/megacheck (from $GOPATH)
can't load package: package mvdan.cc/unparam: cannot find package "mvdan.cc/unparam" in any of:
        /usr/local/go/src/mvdan.cc/unparam (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/mvdan.cc/unparam (from $GOPATH)
can't load package: package github.com/dnephin/govet: cannot find package "github.com/dnephin/govet" in any of:
        /usr/local/go/src/github.com/dnephin/govet (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/github.com/dnephin/govet (from $GOPATH)
can't load package: package github.com/mdempsky/maligned: cannot find package "github.com/mdempsky/maligned" in any of:
        /usr/local/go/src/github.com/mdempsky/maligned (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/github.com/mdempsky/maligned (from $GOPATH)
can't load package: package github.com/alexkohler/nakedret: cannot find package "github.com/alexkohler/nakedret" in any of:
        /usr/local/go/src/github.com/alexkohler/nakedret (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/github.com/alexkohler/nakedret (from $GOPATH)
can't load package: package mvdan.cc/interfacer: cannot find package "mvdan.cc/interfacer" in any of:
        /usr/local/go/src/mvdan.cc/interfacer (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/mvdan.cc/interfacer (from $GOPATH)
WARNING: failed to install one or more linters: exit status 1 (installing individually)
can't load package: package honnef.co/go/tools/cmd/megacheck: cannot find package "honnef.co/go/tools/cmd/megacheck" in any of:
        /usr/local/go/src/honnef.co/go/tools/cmd/megacheck (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/honnef.co/go/tools/cmd/megacheck (from $GOPATH)
WARNING: failed to install honnef.co/go/tools/cmd/megacheck: exit status 1
can't load package: package mvdan.cc/unparam: cannot find package "mvdan.cc/unparam" in any of:
        /usr/local/go/src/mvdan.cc/unparam (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/mvdan.cc/unparam (from $GOPATH)
WARNING: failed to install mvdan.cc/unparam: exit status 1
can't load package: package github.com/dnephin/govet: cannot find package "github.com/dnephin/govet" in any of:
        /usr/local/go/src/github.com/dnephin/govet (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/github.com/dnephin/govet (from $GOPATH)
WARNING: failed to install github.com/dnephin/govet: exit status 1
can't load package: package github.com/mdempsky/maligned: cannot find package "github.com/mdempsky/maligned" in any of:
        /usr/local/go/src/github.com/mdempsky/maligned (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/github.com/mdempsky/maligned (from $GOPATH)
WARNING: failed to install github.com/mdempsky/maligned: exit status 1
can't load package: package github.com/alexkohler/nakedret: cannot find package "github.com/alexkohler/nakedret" in any of:
        /usr/local/go/src/github.com/alexkohler/nakedret (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/github.com/alexkohler/nakedret (from $GOPATH)
WARNING: failed to install github.com/alexkohler/nakedret: exit status 1
can't load package: package mvdan.cc/interfacer: cannot find package "mvdan.cc/interfacer" in any of:
        /usr/local/go/src/mvdan.cc/interfacer (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/mvdan.cc/interfacer (from $GOPATH)
WARNING: failed to install mvdan.cc/interfacer: exit status 1
gometalinter.v2: error: failed to install the following linters: honnef.co/go/tools/cmd/megacheck, mvdan.cc/unparam, github.com/dnephin/govet, github.com/mdempsky/maligned, github.com/alexkohler/nakedret, mvdan.cc/interfacer
```

It's trying to install .v1 metalinter's instead of .v2 for some reason

**Comment by dnephin** [comment]
This should be fixed by #405, we just need to tag v2.0.1

**Comment by dnephin** [comment]
The release is now tagged, let me know if you still see the problem.

**Comment by stevenh** [comment]
Re-ran to get -u and then gometalinter.v2 --install and no change I'm afraid.

**Comment by stevenh** [comment]
Tried to get the actual version it downloaded but --version only reports "master" which isn't very useful :(

**Comment by stevenh** [comment]
git log reports:
```commit 317b1bdd8afb75751bf686f072cef745670303a3 (HEAD -> master, tag: v2.0.1, origin/master, origin/HEAD)```

So looks like its still broken I'm afraid.

**Comment by dnephin** [comment]
I just tried it in a clean environment:

```
$ go get -u gopkg.in/alecthomas/gometalinter.v2
$ gometalinter.v2 --install
Installing:
  ...
$
```
( no error)

**Comment by stevenh** [comment]
This isn't a clean env it already has v1 installed:
```shell
> go get -u gopkg.in/alecthomas/gometalinter.v2
> gometalinter.v2 --install
Installing:
  deadcode
  dupl
  errcheck
  gas
  goconst
  gocyclo
  goimports
  golint
  gosimple
  gotype
  gotypex
  ineffassign
  interfacer
  lll
  maligned
  megacheck
  misspell
  nakedret
  safesql
  staticcheck
  structcheck
  unconvert
  unparam
  unused
  varcheck
  vet
can't load package: package honnef.co/go/tools/cmd/megacheck: cannot find package "honnef.co/go/tools/cmd/megacheck" in any of:
        /usr/local/go/src/honnef.co/go/tools/cmd/megacheck (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/honnef.co/go/tools/cmd/megacheck (from $GOPATH)
can't load package: package github.com/alexkohler/nakedret: cannot find package "github.com/alexkohler/nakedret" in any of:
        /usr/local/go/src/github.com/alexkohler/nakedret (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/github.com/alexkohler/nakedret (from $GOPATH)
can't load package: package github.com/dnephin/govet: cannot find package "github.com/dnephin/govet" in any of:
        /usr/local/go/src/github.com/dnephin/govet (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/github.com/dnephin/govet (from $GOPATH)
can't load package: package mvdan.cc/interfacer: cannot find package "mvdan.cc/interfacer" in any of:
        /usr/local/go/src/mvdan.cc/interfacer (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/mvdan.cc/interfacer (from $GOPATH)
can't load package: package github.com/mdempsky/maligned: cannot find package "github.com/mdempsky/maligned" in any of:
        /usr/local/go/src/github.com/mdempsky/maligned (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/github.com/mdempsky/maligned (from $GOPATH)
can't load package: package mvdan.cc/unparam: cannot find package "mvdan.cc/unparam" in any of:
        /usr/local/go/src/mvdan.cc/unparam (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/mvdan.cc/unparam (from $GOPATH)
WARNING: failed to install one or more linters: exit status 1 (installing individually)
can't load package: package honnef.co/go/tools/cmd/megacheck: cannot find package "honnef.co/go/tools/cmd/megacheck" in any of:
        /usr/local/go/src/honnef.co/go/tools/cmd/megacheck (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/honnef.co/go/tools/cmd/megacheck (from $GOPATH)
WARNING: failed to install honnef.co/go/tools/cmd/megacheck: exit status 1
can't load package: package github.com/alexkohler/nakedret: cannot find package "github.com/alexkohler/nakedret" in any of:
        /usr/local/go/src/github.com/alexkohler/nakedret (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/github.com/alexkohler/nakedret (from $GOPATH)
WARNING: failed to install github.com/alexkohler/nakedret: exit status 1
can't load package: package github.com/dnephin/govet: cannot find package "github.com/dnephin/govet" in any of:
        /usr/local/go/src/github.com/dnephin/govet (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/github.com/dnephin/govet (from $GOPATH)
WARNING: failed to install github.com/dnephin/govet: exit status 1
can't load package: package mvdan.cc/interfacer: cannot find package "mvdan.cc/interfacer" in any of:
        /usr/local/go/src/mvdan.cc/interfacer (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/mvdan.cc/interfacer (from $GOPATH)
WARNING: failed to install mvdan.cc/interfacer: exit status 1
can't load package: package github.com/mdempsky/maligned: cannot find package "github.com/mdempsky/maligned" in any of:
        /usr/local/go/src/github.com/mdempsky/maligned (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/github.com/mdempsky/maligned (from $GOPATH)
WARNING: failed to install github.com/mdempsky/maligned: exit status 1
can't load package: package mvdan.cc/unparam: cannot find package "mvdan.cc/unparam" in any of:
        /usr/local/go/src/mvdan.cc/unparam (from $GOROOT)
        /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters/src/mvdan.cc/unparam (from $GOPATH)
WARNING: failed to install mvdan.cc/unparam: exit status 1
gometalinter.v2: error: failed to install the following linters: honnef.co/go/tools/cmd/megacheck, github.com/alexkohler/nakedret, github.com/dnephin/govet, mvdan.cc/interfacer, github.com/mdempsky/maligned, mvdan.cc/unparam```

**Comment by stevenh** [comment]
Go environment vars set are:
```shell
env |grep GO
GOPATH=/data/go
GOHOME=/data/go
GOBIN=/data/go/bin
```

**Comment by stevenh** [comment]
Running with -d provides some hits on what the issue is:
```shell
> gometalinter.v2 --install -d
DEBUG: found vendored linters at /data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters, updating environment
DEBUG: PATH=/sbin:/bin:/usr/sbin:/data/go/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
DEBUG: GOPATH=/data/go/src/gopkg.in/alecthomas/gometalinter.v1/_linters
DEBUG: GOBIN=/data/go/bin
```
So gometalinter.v2 is still trying to us gometalinter.v1 linter source, hence the issue.
Looking at the source I believe the issue is the search path still includes v1:
https://github.com/alecthomas/gometalinter/blob/master/main.go#L24

**Comment by dnephin** [comment]
Ah, yes it does. I guess it's fine to remove v1 from that list now.

A workaround (if anyone else hits this issue) is to `rm -r $GOPATH/src/gopkg.in/alecthomas/gometalinter.v1`

**Comment by alecthomas** [comment]
BTW, binaries are now built with cgo disabled.

**Comment by gyliu513** [comment]
I encounter same issue in istio at https://github.com/istio/istio/issues/6136 , and have to workaround this issue by copying the files as https://github.com/istio/istio/issues/6136#issuecomment-396104421 , can anyone help how to fix this without copy files manually?
